/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Property {
    id: PropertyId;
    title: string;
    propertyType: PropertyType;
    imageUrls: Array<string>;
    createdAt: bigint;
    description: string;
    amenities: Array<string>;
    isFeatured: boolean;
    squareFootage: bigint;
    price: bigint;
    location: string;
}
export interface Inquiry {
    submittedAt: bigint;
    propertyId: PropertyId;
    visitorName: string;
    message: string;
    visitorEmail: string;
    visitorPhone: string;
}
export type PropertyId = bigint;
export enum PropertyType {
    Commercial = "Commercial",
    Residential = "Residential"
}
export interface backendInterface {
    addProperty(title: string, description: string, price: bigint, squareFootage: bigint, location: string, propertyType: PropertyType, amenities: Array<string>, imageUrls: Array<string>, isFeatured: boolean): Promise<PropertyId>;
    deleteProperty(id: PropertyId): Promise<void>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getAllProperties(): Promise<Array<Property>>;
    getFeaturedProperties(): Promise<Array<Property>>;
    getProperty(id: PropertyId): Promise<Property>;
    searchProperties(propertyType: PropertyType | null, maxBudget: bigint | null, locationKeyword: string | null): Promise<Array<Property>>;
    submitInquiry(propertyId: PropertyId, visitorName: string, visitorEmail: string, visitorPhone: string, message: string): Promise<void>;
    updateProperty(id: PropertyId, title: string, description: string, price: bigint, squareFootage: bigint, location: string, propertyType: PropertyType, amenities: Array<string>, imageUrls: Array<string>, isFeatured: boolean): Promise<void>;
}
import type { Property as _Property, PropertyId as _PropertyId, PropertyType as _PropertyType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProperty(arg0: string, arg1: string, arg2: bigint, arg3: bigint, arg4: string, arg5: PropertyType, arg6: Array<string>, arg7: Array<string>, arg8: boolean): Promise<PropertyId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProperty(arg0, arg1, arg2, arg3, arg4, to_candid_PropertyType_n1(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProperty(arg0, arg1, arg2, arg3, arg4, to_candid_PropertyType_n1(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8);
            return result;
        }
    }
    async deleteProperty(arg0: PropertyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProperty(arg0);
            return result;
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return result;
        }
    }
    async getAllProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProperties();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProperties();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProperties();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProperties();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: PropertyId): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_Property_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_Property_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchProperties(arg0: PropertyType | null, arg1: bigint | null, arg2: string | null): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProperties(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProperties(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitInquiry(arg0: PropertyId, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateProperty(arg0: PropertyId, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: string, arg6: PropertyType, arg7: Array<string>, arg8: Array<string>, arg9: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProperty(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_PropertyType_n1(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProperty(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_PropertyType_n1(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
            return result;
        }
    }
}
function from_candid_PropertyType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Property_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Property {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PropertyId;
    title: string;
    propertyType: _PropertyType;
    imageUrls: Array<string>;
    createdAt: bigint;
    description: string;
    amenities: Array<string>;
    isFeatured: boolean;
    squareFootage: bigint;
    price: bigint;
    location: string;
}): {
    id: PropertyId;
    title: string;
    propertyType: PropertyType;
    imageUrls: Array<string>;
    createdAt: bigint;
    description: string;
    amenities: Array<string>;
    isFeatured: boolean;
    squareFootage: bigint;
    price: bigint;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        propertyType: from_candid_PropertyType_n6(_uploadFile, _downloadFile, value.propertyType),
        imageUrls: value.imageUrls,
        createdAt: value.createdAt,
        description: value.description,
        amenities: value.amenities,
        isFeatured: value.isFeatured,
        squareFootage: value.squareFootage,
        price: value.price,
        location: value.location
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Commercial: null;
} | {
    Residential: null;
}): PropertyType {
    return "Commercial" in value ? PropertyType.Commercial : "Residential" in value ? PropertyType.Residential : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Array<Property> {
    return value.map((x)=>from_candid_Property_n4(_uploadFile, _downloadFile, x));
}
function to_candid_PropertyType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType | null): [] | [_PropertyType] {
    return value === null ? candid_none() : candid_some(to_candid_PropertyType_n1(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    Commercial: null;
} | {
    Residential: null;
} {
    return value == PropertyType.Commercial ? {
        Commercial: null
    } : value == PropertyType.Residential ? {
        Residential: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
