/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Inquiry {
  'submittedAt' : bigint,
  'propertyId' : PropertyId,
  'visitorName' : string,
  'message' : string,
  'visitorEmail' : string,
  'visitorPhone' : string,
}
export interface Property {
  'id' : PropertyId,
  'title' : string,
  'propertyType' : PropertyType,
  'imageUrls' : Array<string>,
  'createdAt' : bigint,
  'description' : string,
  'amenities' : Array<string>,
  'isFeatured' : boolean,
  'squareFootage' : bigint,
  'price' : bigint,
  'location' : string,
}
export type PropertyId = bigint;
export type PropertyType = { 'Commercial' : null } |
  { 'Residential' : null };
export interface _SERVICE {
  'addProperty' : ActorMethod<
    [
      string,
      string,
      bigint,
      bigint,
      string,
      PropertyType,
      Array<string>,
      Array<string>,
      boolean,
    ],
    PropertyId
  >,
  'deleteProperty' : ActorMethod<[PropertyId], undefined>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getFeaturedProperties' : ActorMethod<[], Array<Property>>,
  'getProperty' : ActorMethod<[PropertyId], Property>,
  'searchProperties' : ActorMethod<
    [[] | [PropertyType], [] | [bigint], [] | [string]],
    Array<Property>
  >,
  'submitInquiry' : ActorMethod<
    [PropertyId, string, string, string, string],
    undefined
  >,
  'updateProperty' : ActorMethod<
    [
      PropertyId,
      string,
      string,
      bigint,
      bigint,
      string,
      PropertyType,
      Array<string>,
      Array<string>,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];