/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PropertyType = IDL.Variant({
  'Commercial' : IDL.Null,
  'Residential' : IDL.Null,
});
export const PropertyId = IDL.Nat;
export const Inquiry = IDL.Record({
  'submittedAt' : IDL.Int,
  'propertyId' : PropertyId,
  'visitorName' : IDL.Text,
  'message' : IDL.Text,
  'visitorEmail' : IDL.Text,
  'visitorPhone' : IDL.Text,
});
export const Property = IDL.Record({
  'id' : PropertyId,
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'imageUrls' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'isFeatured' : IDL.Bool,
  'squareFootage' : IDL.Nat,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProperty' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        PropertyType,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [PropertyId],
      [],
    ),
  'deleteProperty' : IDL.Func([PropertyId], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getProperty' : IDL.Func([PropertyId], [Property], ['query']),
  'searchProperties' : IDL.Func(
      [IDL.Opt(PropertyType), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'submitInquiry' : IDL.Func(
      [PropertyId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateProperty' : IDL.Func(
      [
        PropertyId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        PropertyType,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PropertyType = IDL.Variant({
    'Commercial' : IDL.Null,
    'Residential' : IDL.Null,
  });
  const PropertyId = IDL.Nat;
  const Inquiry = IDL.Record({
    'submittedAt' : IDL.Int,
    'propertyId' : PropertyId,
    'visitorName' : IDL.Text,
    'message' : IDL.Text,
    'visitorEmail' : IDL.Text,
    'visitorPhone' : IDL.Text,
  });
  const Property = IDL.Record({
    'id' : PropertyId,
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'imageUrls' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'isFeatured' : IDL.Bool,
    'squareFootage' : IDL.Nat,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addProperty' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          PropertyType,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [PropertyId],
        [],
      ),
    'deleteProperty' : IDL.Func([PropertyId], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getProperty' : IDL.Func([PropertyId], [Property], ['query']),
    'searchProperties' : IDL.Func(
        [IDL.Opt(PropertyType), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'submitInquiry' : IDL.Func(
        [PropertyId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateProperty' : IDL.Func(
        [
          PropertyId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          PropertyType,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };